### ISSUE TITLE
Potential issue use of default struct as "nil" comparison value for versioned serialization

### ISSUE THREAD

**Issue by tychedelia** [tychedelia/kafka-protocol-rs#1]
Updates to protocol added structs in responses that previously had been unnecessary for serialization logic. Because structs don't have an obvious zero value, this makes it difficult to generate an error when a struct has been erroneously modified when encoding a version that does not support that struct. To work around this, we are using `Default::default` as a zero value to compare if the struct has been modified, but it's unclear whether this is a safe indicator, or whether default can represent a valid state for some structs. In practice, this may not be an issue.

**Comment by 0x1991babe** [comment]
It appears that all of the structs in `FetchResponse` have sensible `-1` defaults, which should make this safe to use as a nil comparison value. However, `FetchSnapshotResponse`, [is missing default values](https://github.com/0x1991babe/kafka-protocol-rs/blob/main/src/messages/fetch_snapshot_response.rs#L88-L89).

This is a new API, so may have just been overlooked [in the upstream source](https://github.com/apache/kafka/blob/trunk/clients/src/main/resources/common/message/FetchSnapshotResponse.json#L40-L41). Unclear whether `leader_id: 0` and `snapshot_id: 0` are valid values. Will file PR upstream for consistency.

**Comment by tychedelia** [comment]
Upstream PR was closed, this is for Raft anyway, which is pretty low risk for the probable use cases of this repo.
