### ISSUE TITLE
Missing #[builder(default)] on builder impls

### ISSUE THREAD

**Issue by tychedelia** [tychedelia/kafka-protocol-rs#33]
See https://github.com/colin-kiegel/rust-derive-builder/issues/261.

**Comment by rukai** [comment]
Ooooh, does this fix the issue where literally every field of the builder needs to be set? I didn't think to report it as an issue but did think it was a strange design 😅

**Comment by tychedelia** [comment]
> Ooooh, does this fix the issue where literally every field of the builder needs to be set? I didn't think to report it as an issue but did think it was a strange design 😅

Yes! I thought this was just a design oversight too, but dug deeper. Seems a bit strange this isn't the default behavior, as I can't imagine a situation where you wouldn't want to fall back to default. In general, I find the builders much more ergonomic then changing a bunch of mutable fields, particularly after we decided to make all the messages non-exhaustive.
