### ISSUE TITLE
Run Clippy (and Rustfmt?) in CI

### ISSUE THREAD

**Issue by tychedelia** [tychedelia/kafka-protocol-rs#50]
We missed a pretty useful suggestion, noticed in https://github.com/tychedelia/kafka-protocol-rs/pull/49. We should be running Clippy in our CI, and potentially rustfmt, although I know we've had questions before about whether the codegen files should be formatted since it can make reading them a bit more confusing.

**Comment by tychedelia** [comment]
We already run rustfmt.

**Comment by rukai** [comment]
I'll make a pr for this, I've setup clippy on a few repos at this point
